# Generated by Django 5.2.4 on 2025-08-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='portal_code',
            new_name='postal_code',
        ),
    ]
